language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx-2
  
script: "bundle exec rspec spec"

before_install:
  - gem install bundler

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
